#!/usr/bin/env bash
set -e

# -u: needs to write to vendor/
# Composer prints some warning when git-cloning
# due to the user not being in /etc/passwd

docker-compose run \
    -u $(id -u) \
    cli \
    composer $@
