#!/usr/bin/env bash
set -e

# -u: needs to write to vendor/
# Composer prints some warning when git-cloning
# due to the user not being in /etc/passwd

docker run \
    -v $(pwd):/srv/annotations \
    -v /srv/annotations/var/logs \
    -u $(id -u) \
    -t \
    annotations_cli \
    composer $@
