version: '3'

services: 
    ci:
        build: 
            context: .
            dockerfile: Dockerfile.ci
        volumes:
            - ./build:/srv/annotations/build
            - ./config/container.php:/srv/annotations/config.php
        env_file:
            - dev.env
        depends_on:
            - web
