version: '3'

services:
    composer:
        build:
            args:
                composer_dev: --no-dev
    composer-dev:
        build:
            context: .
            dockerfile: Dockerfile.composer
            args:
                composer_dev:
        image: elifesciences/annotations_composer_dev:${IMAGE_TAG}
        command: /bin/bash
    fpm:
        env_file:
            - ci.env
    cli:
        env_file:
            - ci.env
    ci:
        build:
            context: .
            dockerfile: Dockerfile.ci
            args:
                image_tag: ${IMAGE_TAG}
        image: elifesciences/annotations_ci:${IMAGE_TAG}
        env_file:
            - ci.env
        depends_on:
            - composer-dev
