version: '3'

services:
    composer:
        build:
            context: .
            dockerfile: Dockerfile.composer
            args:
                composer_dev: ${COMPOSER_DEV}
        image: elifesciences/annotations_composer:${IMAGE_TAG}
        command: /bin/bash
    web:
        image: nginx:1.13.7
        ports:
            - "8080:80"
        volumes:
            - ./.docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
            - web:/srv/annotations/web
        depends_on:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: Dockerfile.fpm
            args:
                image_tag: ${IMAGE_TAG}
                dependencies_api_dummy: "${DEPENDENCIES_API_DUMMY}"
                dependencies_hypothesis_dummy: "${DEPENDENCIES_HYPOTHESIS_DUMMY}"
        image: elifesciences/annotations_fpm:${IMAGE_TAG}
        volumes:
            - ./.docker/config.php:/srv/annotations/config.php
            - logs:/srv/annotations/var/logs
            - web:/srv/annotations/web
        depends_on:
            - api_dummy
            - composer
            - hypothesis_dummy
            - goaws
    cli:
        build:
            context: .
            dockerfile: Dockerfile.cli
            args:
                image_tag: ${IMAGE_TAG}
                dependencies_api_dummy: "${DEPENDENCIES_API_DUMMY}"
                dependencies_hypothesis_dummy: "${DEPENDENCIES_HYPOTHESIS_DUMMY}"
        image: elifesciences/annotations_cli:${IMAGE_TAG}
        volumes:
            - ./.docker/config.php:/srv/annotations/config.php
            - logs:/srv/annotations/var/logs
        depends_on:
            - api_dummy
            - composer
            - hypothesis_dummy
            - goaws
    goaws:
        image: elifesciences/goaws:1.0.1
        ports:
            - 4100:4100
        volumes:
            - ./.docker/goaws.yaml:/conf/goaws.yaml
    logger:
        image: busybox:1.27.2
        volumes:
            - logs:/logs
        # be careful, this will only tail already existing files
        command: tail -f /logs/all.json
        depends_on:
            - cli
    api_dummy:
        image: elifesciences/api-dummy:${DEPENDENCIES_API_DUMMY}
    hypothesis_dummy:
        image: elifesciences/hypothesis-dummy:${DEPENDENCIES_HYPOTHESIS_DUMMY}

volumes:
    logs:
    web:
