FROM composer:1.6.3

COPY composer.json \
    composer.lock \
    ./

RUN composer --no-interaction install --no-dev --ignore-platform-reqs --no-autoloader --no-scripts --no-suggest

COPY src/ src/

RUN composer --no-interaction dump-autoload --no-dev --classmap-authoritative
RUN composer --no-interaction run-script post-install-cmd
