version: '3'

services:
    web:
        image: nginx:1.13.7
        ports:
            - "8080:80"
        volumes:
            - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
            # can we avoid this by removing try_files?
            - ./web:/srv/annotations/web
        depends_on:
            - fpm
    fpm:
        build: 
            context: .
            dockerfile: Dockerfile.fpm
        volumes:
            - ./config/container.php:/srv/annotations/config.php
        env_file:
            - dev.env
    cli:
        build: 
            context: .
            dockerfile: Dockerfile.cli
        volumes:
            - ./config/container.php:/srv/annotations/config.php
        env_file:
            - dev.env
