version: '3'

services:
    composer-dev:
        build:
            context: .
            dockerfile: Dockerfile.composer.dev
        image: elifesciences/annotations_composer:${IMAGE_TAG}-dev
        command: /bin/bash
    composer-no-dev:
        build:
            context: .
            dockerfile: Dockerfile.composer.no-dev
        image: elifesciences/annotations_composer:${IMAGE_TAG}-no-dev
        command: /bin/bash
    web:
        image: nginx:1.13.7
        ports:
            - "8080:80"
        volumes:
            - ./.docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
            - web:/srv/annotations/web
        depends_on:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: Dockerfile.fpm
            args:
                composer_type: ${COMPOSER_TYPE}
                image_tag: ${IMAGE_TAG}
                dependencies_api_dummy: "${DEPENDENCIES_API_DUMMY}"
                dependencies_hypothesis_dummy: "${DEPENDENCIES_HYPOTHESIS_DUMMY}"
        image: elifesciences/annotations_fpm:${IMAGE_TAG}
        volumes:
            - ./config/container.php:/srv/annotations/config.php
            - logs:/srv/annotations/var/logs
            - web:/srv/annotations/web
        env_file:
            - dev.env
        depends_on:
            - api_dummy
            - composer-${COMPOSER_TYPE}
            - hypothesis_dummy
            - goaws
    cli:
        build:
            context: .
            dockerfile: Dockerfile.cli
            args:
                composer_type: ${COMPOSER_TYPE}
                image_tag: ${IMAGE_TAG}
                dependencies_api_dummy: "${DEPENDENCIES_API_DUMMY}"
                dependencies_hypothesis_dummy: "${DEPENDENCIES_HYPOTHESIS_DUMMY}"
        image: elifesciences/annotations_cli:${IMAGE_TAG}
        volumes:
            - ./config/container.php:/srv/annotations/config.php
            - logs:/srv/annotations/var/logs
        env_file:
            - dev.env
        depends_on:
            - api_dummy
            - composer-${COMPOSER_TYPE}
            - hypothesis_dummy
            - goaws
    goaws:
        image: elifesciences/goaws:1.0.1
        ports:
            - 4100:4100
        volumes:
            - ./.docker/goaws.yaml:/conf/goaws.yaml
    logger:
        image: busybox:1.27.2
        volumes:
            - logs:/logs
        # be careful, this will only tail already existing files
        command: tail -f /logs/all.json
        depends_on:
            - cli
    api_dummy:
        image: elifesciences/api-dummy:${DEPENDENCIES_API_DUMMY}
    hypothesis_dummy:
        image: elifesciences/hypothesis-dummy:${DEPENDENCIES_HYPOTHESIS_DUMMY}
    ci:
        build:
            context: .
            dockerfile: Dockerfile.ci
            args:
                image_tag: ${IMAGE_TAG}
        image: elifesciences/annotations_ci:${IMAGE_TAG}
        volumes:
            - ./config/container.php:/srv/annotations/config.php
        env_file:
            - dev.env
        depends_on:
            - composer-dev

volumes:
    logs:
    web:
