version: '3'


services:
    web:
        image: nginx:1.13.7
        ports:
            # TODO: must be configurable/random
            - "8080:80"
        volumes:
            - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
            # TODO: can we avoid this by removing try_files?
            - ./web:/srv/annotations/web
        depends_on:
            - fpm
    fpm:
        build: 
            context: .
            args:
                dependencies_api_dummy: "${DEPENDENCIES_API_DUMMY}"
            dockerfile: Dockerfile.fpm
        image: elifesciences/annotations_fpm:${IMAGE_TAG}
        volumes:
            - ./config/container.php:/srv/annotations/config.php
            - logs:/srv/annotations/var/logs
        env_file:
            - dev.env
        depends_on:
            - api_dummy
            - hypothesis_dummy
            - goaws
    cli:
        build: 
            context: .
            args:
                dependencies_api_dummy: "${DEPENDENCIES_API_DUMMY}"
            dockerfile: Dockerfile.cli
        image: elifesciences/annotations_cli:${IMAGE_TAG}
        volumes:
            - ./config/container.php:/srv/annotations/config.php
            - logs:/srv/annotations/var/logs
        env_file:
            - dev.env
        depends_on:
            - api_dummy
            - hypothesis_dummy
            - goaws
    goaws:
        image: elifesciences/goaws:1.0.1
        ports:
            - 4100:4100
        volumes:
            - ./config/goaws.yaml:/conf/goaws.yaml
    logger:
        image: busybox:1.27.2
        volumes:
            - logs:/logs
        # be careful, this will only tail already existing files
        command: tail -f /logs/all.json
        depends_on:
            - cli
    api_dummy:
        image: elifesciences/api-dummy:${DEPENDENCIES_API_DUMMY}
    hypothesis_dummy:
        image: elifesciences/hypothesis-dummy:${DEPENDENCIES_HYPOTHESIS_DUMMY}
    ci:
        build: 
            context: .
            args:
                commit: "${IMAGE_TAG}"
            dockerfile: Dockerfile.ci
        image: elifesciences/annotations_ci:${IMAGE_TAG}
        volumes:
            - ./build:/srv/annotations/build
            - ./config/container.php:/srv/annotations/config.php
        env_file:
            - dev.env
        depends_on:
            - web
            - cli

volumes:
    logs:
