annotations:
    path: /annotations
    defaults:
         _controller: AppBundle:Annotations:get
         _format: json
    methods: [GET]

homepage:
    path: /
    defaults:
         _controller: AppBundle:Default:index

ping:
    path: /ping
    defaults:
         _controller: AppBundle:Status:ping
