services:

    elife.hypothesis_client.client:
        class: eLife\HypothesisClient\HttpClient\Guzzle6HttpClient
        arguments:
          - '@csa_guzzle.client.hypothesis_api'

    elife.hypothesis_client.client.warning_checking:
        class: eLife\HypothesisClient\HttpClient\WarningCheckingHttpClient
        decorates: elife.hypothesis_client.client
        arguments:
          - '@elife.hypothesis_client.client.warning_checking.inner'
          - '@monolog.logger.api'

    elife.hypothesis_client.client.user_agent_prepending:
        class: eLife\HypothesisClient\HttpClient\UserAgentPrependingHttpClient
        decorates: elife.hypothesis_client.client
        arguments:
          - '@elife.hypothesis_client.client.warning_checking.inner'
          - '@="HypothesisAnnotations"'

    elife.hypothesis_client.api_sdk:
        class: eLife\HypothesisClient\ApiSdk\ApiSdk
        public: false
        arguments:
          - '@elife.hypothesis_client.client'

    elife.hypothesis_client.api_sdk.annotations:
        class: eLife\HypothesisClient\ApiSdk\Client\Annotations
        factory: ['@elife.hypothesis_client.api_sdk', annotations]

    elife.hypothesis_client.api_sdk.annotations.serializer:
        class: eLife\HypothesisClient\AppBundle\Serializer\AnnotationNormalizer

    elife.annotations.guzzle.cache.client:
        class: GuzzleHttp\Client
        public: false
        arguments:
          - connect_timeout: 1
            timeout: 2
        tags:
          - name: csa_guzzle.client

    elife.journal.listener.cache_control:
        class: eLife\HypothesisClient\AppBundle\EventListener\CacheControlSubscriber
        tags:
          - name: kernel.event_subscriber

    elife.hypothesis_client.listener.network_problem:
        class: eLife\HypothesisClient\AppBundle\EventListener\NetworkProblemSubscriber
        tags:
          - name: kernel.event_subscriber
